OMAP: BRIDGE: Check Patch Bridge Cleanup
Cleanup most of the things that checkpatch complains about.
Some of them are:
	- Indent style
	- WARNING: do not add new typedefs
	- ERROR: return is not a function, parentheses are
	  not required

Signed-off-by: Omar Ramirez Luna <x00omar@ti.com>
Acked-by: Hari Kanigeri <h-kanigeri2@ti.com>
Acked-by: Ramesh Gupta <grgupta@ti.com>